name: ipyleaflet-dev
channels:
  - conda-forge
dependencies:
  - pip
  - wheel
  - flake8
  - jupyterlab~=4.0
  - jupyter-packaging~=0.12
  - ipywidgets
  - xyzservices
  - branca
  - traittypes
  - pandas
  - yarn~=3.0
