name: ipyleaflet
channels:
  - conda-forge
dependencies:
  - nodejs=14.11
  - ipyleaflet=0.14.0
  - jupyterlab=3
  - scipy
  - bqplot
  - rasterio
  - tqdm
  - requests
  - pillow
  - matplotlib
  - flask
  - branca
  - geopandas
  - netcdf4
  - xarray
