name: ipyleaflet-docs

channels:
  - conda-forge

dependencies:
  - pip
  - yarn~=3.0
  - jupyterlab~=4.0
  - jupyter-packaging~=0.12
  - jupyter-sphinx
  - scipy
  - netcdf4
  - geopandas
  - xarray
  - branca
  - shapely
  - pydata-sphinx-theme
  - jupyterlite-sphinx
  - jupyterlite-xeus-python >=0.9.2,<0.10
  - pip:
      - build
      - ../python/jupyter_leaflet
      - ../python/ipyleaflet
