name: ipyleaflet-docs

channels:
  - conda-forge

dependencies:
  - yarn
  - jupyterlab
  - jupyter-packaging
  - jupyter-sphinx
  - scipy
  - netcdf4
  - geopandas
  - xarray
  - branca
  - shapely
  - pydata-sphinx-theme

  - pip:
    - ..
    - jupyterlite-sphinx