name: ipycanvas
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy
  - ipywidgets
  - traittypes
  - xyzservices
  - branca
  - pip:
      - ../python/ipyleaflet_core
      - ../python/ipyleaflet
